doctrine:
    dbal:
        driver:   pdo_pgsql
        url:      pgsql://postgres@127.0.0.1/insajder-migration?charset=utf8&serverVersion=9
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                type: yml
                dir: "%kernel.root_dir%/Resources/config/doctrine/App"
                is_bundle: false
                prefix: "App\\Entity"
                alias: App
