# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    App\Importer\NewscoopApiImporter:
        public: true
        arguments:
            $client: '@GuzzleHttp\ClientInterface'

    App\Importer\NewscoopImageApiImporter:
        public: true
        arguments:
            $client: '@GuzzleHttp\ClientInterface'

    App\Publisher\TwigHtmlPublisher:
        public: true
        arguments:
            $twig: '@twig'
            $projectDir: '%kernel.project_dir%'

    AHS\Publisher\NinjsPublisher:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Publisher\ExternalDataPublisher:
        public: true

    AHS\Factory\NinjsFactory:
        public: true
    AHS\Factory\FactoryInterface: '@AHS\Factory\NinjsFactory'

    AHS\Serializer\NinjsSerializer:
        class: AHS\Serializer\NinjsSerializer
    AHS\Serializer\SerializerInterface: '@AHS\Serializer\NinjsSerializer'

    App\Factory\InsajderNinjsFactory:
        public: true

    App\Consumer\NewscoopImportConsumer:
        public: true

    App\Consumer\PublisherExternalDataConsumer:
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Factory,Importer,Publisher,Consumer}'

    metadata_aware_name_converter:
        class: Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter
